/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beast_mascot_distribution_MascotNative2 */

#ifndef _Included_beast_mascot_distribution_MascotNative2
#define _Included_beast_mascot_distribution_MascotNative2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beast_mascot_distribution_MascotNative2
 * Method:    setup
 * Signature: ([IIDDIIIZ)V
 */
JNIEXPORT void JNICALL Java_beast_mascot_distribution_MascotNative2_setup
  (JNIEnv *, jobject, jintArray, jint, jdouble, jdouble, jint, jint, jint, jboolean);

/*
 * Class:     beast_mascot_distribution_MascotNative2
 * Method:    calculateLogP
 * Signature: (ZI[I[I[D[I)D
 */
JNIEXPORT jdouble JNICALL Java_beast_mascot_distribution_MascotNative2_calculateLogP
  (JNIEnv *, jobject, jboolean, jint, jintArray, jintArray, jdoubleArray, jintArray);

/*
 * Class:     beast_mascot_distribution_MascotNative2
 * Method:    setUpDynamics
 * Signature: ([D[D[[I[D)V
 */
JNIEXPORT void JNICALL Java_beast_mascot_distribution_MascotNative2_setUpDynamics
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jobjectArray, jdoubleArray);

/*
 * Class:     beast_mascot_distribution_MascotNative2
 * Method:    getStateProb
 * Signature: (I[D)V
 */
JNIEXPORT void JNICALL Java_beast_mascot_distribution_MascotNative2_getStateProb
  (JNIEnv *, jobject, jint, jdoubleArray);

/*
 * Class:     beast_mascot_distribution_MascotNative2
 * Method:    storeState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_beast_mascot_distribution_MascotNative2_storeState
  (JNIEnv *, jobject);

/*
 * Class:     beast_mascot_distribution_MascotNative2
 * Method:    restoreState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_beast_mascot_distribution_MascotNative2_restoreState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
